---
title: "Water Quality Dashboard"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

# libraries
library(flexdashboard)
library(leaflet)
library(here)
# library(tbeptools)
devtools::load_all(here())
library(tidyverse)
library(patchwork)
library(shiny)

# local file path
xlsx <- here('data-raw', '2018_Results_Updated.xls')

# import data
epcdata <- read_importwq(xlsx, download_latest_epchc = F)
```


```{r reactives}

shinyjs::useShinyjs(rmd = TRUE)
observeEvent(input$reset_input, {
      shinyjs::reset("otbchltrg")
      shinyjs::reset("hbchltrg")
      shinyjs::reset("mtbchltrg")
      shinyjs::reset("ltbchltrg")
      shinyjs::reset("otblatrg")
      shinyjs::reset("hblatrg")
      shinyjs::reset("mtblatrg")
      shinyjs::reset("ltblatrg")
    })

# format target inputs
trginps <- reactive({

  # inputs
  trginps <- tibble(
      otbchltrg = input$otbchltrg,
      hbchltrg = input$hbchltrg, 
      mtbchltrg = input$mtbchltrg, 
      ltbchltrg = input$ltbchltrg,
      otblatrg = input$otblatrg,
      hblatrg = input$hblatrg,
      mtblatrg = input$mtblatrg,
      ltblatrg = input$ltblatrg
    ) %>% 
    gather('var', 'val') %>% 
    mutate(
      bay_segment = gsub('chltrg$|latrg$', '', var),
      bay_segment = toupper(bay_segment), 
      var = gsub('^.*(chltrg$|latrg$)', '\\1', var), 
      var = gsub('trg$', '_target', var), 
      var = gsub('^chl', 'chla', var)
    ) %>% 
    spread(var, val)
  
  # se diff for targets
  trgs <- targets %>% 
    mutate(
      lase1 = la_smallex - la_target, 
      chlase1 = chla_smallex - chla_target, 
      lase2 = la_thresh - la_smallex,
      chlase2 = chla_thresh - chla_smallex
    ) %>% 
    select(bay_segment, name, lase1, chlase1, lase2, chlase2)
  
  # combine with se, estimate new thresholds
  out <- trginps %>% 
    left_join(trgs, by = 'bay_segment') %>% 
    mutate(
      chla_smallex = chla_target + chlase1, 
      chla_thresh = chla_smallex + chlase2,
      la_smallex = la_target + lase1, 
      la_thresh = la_smallex + lase2
    ) %>% 
    select(bay_segment, name, chla_target, chla_smallex, chla_thresh, la_target, la_smallex, la_thresh)
  
  return(out)
  
})

# OTB threshold plot
thrplototb <- reactive({
  
  # inputs
  trginps <- trginps()
  
  req(trginps)
    
  p1 <- show_thrplot(epcdata, bay_segment = "OTB", thr = "chla", trgs = trginps) + 
    ggtitle(NULL)
  p2 <- show_thrplot(epcdata, bay_segment = "OTB", thr = "la", trgs = trginps) + 
    ggtitle(NULL)
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# HB threshold plot
thrplothb <- reactive({
  
  # inputs
  trginps <- trginps()
  
  req(trginps)
    
  p1 <- show_thrplot(epcdata, bay_segment = "HB", thr = "chla", trgs = trginps) + 
    ggtitle(NULL)
  p2 <- show_thrplot(epcdata, bay_segment = "HB", thr = "la", trgs = trginps) + 
    ggtitle(NULL)
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# MTB threshold plot
thrplotmtb <- reactive({
  
  # inputs
  trginps <- trginps()
  
  req(trginps)
  
  p1 <- show_thrplot(epcdata, bay_segment = "MTB", thr = "chla", trgs = trginps) + 
    ggtitle(NULL)
  p2 <- show_thrplot(epcdata, bay_segment = "MTB", thr = "la", trgs = trginps) + 
    ggtitle(NULL)
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# LTB threshold plot
thrplotltb <- reactive({
  
  # inputs
  trginps <- trginps()
  
  req(trginps)
  
  p1 <- show_thrplot(epcdata, bay_segment = "LTB", thr = "chla", trgs = trginps) + 
    ggtitle(NULL)
  p2 <- show_thrplot(epcdata, bay_segment = "LTB", thr = "la", trgs = trginps) + 
    ggtitle(NULL)
  
  p1 + p2 + plot_layout(ncol = 1)
  
})

# attainment matrix
attmat <- reactive({
  
  # input
  trginps <- trginps()
  
  req(trginps)
  
  out <- show_matrix(epcdata, txtsz = NULL, trgs = trginps)
  
  return(out)
  
})
```

Sidebar {.sidebar data-width=400}
===========================================================

#### Chlorophyll threshold

<br>
```{r}
column(12, 
       column(2, 'OTB'), 
       column(10, sliderInput('otbchltrg', NULL, min = 0, max = 20, value = 8.5, step = 0.1, round = F)
       ))
column(12, 
       column(2, 'HB'), 
       column(10, sliderInput('hbchltrg', NULL, min = 0, max = 20, value = 13.2, step = 0.1, round = F)
       ))
column(12, 
       column(2, 'MTB'),
       column(10, sliderInput('mtbchltrg', NULL, min = 0, max = 20, value = 7.4, step = 0.1, round = F)
       ))
column(12, 
       column(2, 'LTB'),
       column(10, sliderInput('ltbchltrg', NULL, min = 0, max = 20, value = 4.6, step = 0.1, round = F)
       ))
```

#### Light attenuation target

<br>
```{r}
column(12, 
       column(2, 'OTB'), 
       column(10, sliderInput('otblatrg', NULL, min = 0, max = 3, value = 0.83, step = 0.01, round = F)
       ))
column(12, 
       column(2, 'HB'), 
       column(10, sliderInput('hblatrg', NULL, min = 0, max = 3, value = 1.58, step = 0.01, round = F)
       ))
column(12, 
       column(2, 'MTB'),
       column(10, sliderInput('mtblatrg', NULL, min = 0, max = 3, value = 0.83, step = 0.01, round = F)
       ))
column(12, 
       column(2, 'LTB'),
       column(10, sliderInput('ltblatrg', NULL, min = 0, max = 3, value = 0.63, step = 0.01, round = F)
       ))

actionButton("reset_input", "Reset inputs")
```

Annual means time series plots
===========================================================

Column {.tabset .tabset-fade data-width=650}
-----------------------------------------------------------------------

### Old Tampa Bay

```{r plot_otb, fig.height = 8, fig.width = 10}
output$thrplototb <- renderPlot({thrplototb()})
plotOutput('thrplototb')
```

### Hillsborough Bay

```{r plot_hb, fig.height = 8, fig.width = 10}
output$thrplothb <- renderPlot({thrplothb()})
plotOutput('thrplothb')
```

### Middle Tampa Bay

```{r plot_mtb, fig.height = 8, fig.width = 10}
output$thrplotmtb <- renderPlot({thrplotmtb()})
plotOutput('thrplotmtb')
```

### Lower Tampa Bay

```{r plot_ltb, fig.height = 8, fig.width = 10}
output$thrplotltb <- renderPlot({thrplotltb()})
plotOutput('thrplotltb')
```

Map
===========================================================

Column {data-width=350}
-----------------------------------------------------------------------

### Map

```{r ecphc_validate}
#Display station locations
wqsites <- epcdata[, c('epchc_station', 'Latitude', 'Longitude')] %>% 
           unique()                                                   
map <- leaflet(wqsites) %>%                                         
              addProviderTiles(providers$CartoDB.Positron) %>% 
              addCircleMarkers(~Longitude, ~Latitude,
                               radius = 6,
                               color = 'black',
                               stroke = FALSE,
                               opacity = 0.8,
                               popup = ~as.character(paste('EPC Station:', epchc_station)), 
                               group = 'Water quality') %>% 
              addLayersControl(overlayGroups = c('Water quality'),
                               options = layersControlOptions(collapsed = FALSE))
map
```

Attainment matrix
===========================================================

### Matrix

```{r}
output$attmat <- renderPlot({attmat()}, width = 400)
plotOutput('attmat')
```
