---
title: "Intro to TBEP Tools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro to TBEP Tools}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = F, warning = F
)
```

```{r setup}
# libraries
library(leaflet)
# library(tbeptools) # remotes::install_github("tbep-tech/tbeptools")
devtools::load_all('.')

# local file path
xlsx <- '2018_Results_Updated.xls'
```

## Download and import EPCHC dataset

```{r epchc_import}
# load data and some light formatting
epcdata <- read_importwq(xlsx, download_latest_epchc = T)
epcdata
```

```{r ecphc_validate}
#Display station locations
wqsites <- epcdata[, c('epchc_station', 'Latitude', 'Longitude')] %>% 
           unique()                                                   

map <- leaflet(wqsites) %>%                                         
              addProviderTiles(providers$CartoDB.Positron) %>% 
              addCircleMarkers(~Longitude, ~Latitude,
                               radius = 6,
                               color = 'black',
                               stroke = FALSE,
                               opacity = 0.8,
                               popup = ~as.character(paste('EPC Station:', epchc_station)), 
                               group = 'Water quality') %>% 
              addLayersControl(overlayGroups = c('Water quality'),
                               options = layersControlOptions(collapsed = FALSE))
map
```

## Plot Mean Annual Chl-a Values by Bay Segment {.tabset}

### Old Tampa Bay

```{r chlplot_otb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "OTB", thr = "chla")
```

### Hillsborough Bay

```{r chlplot_hb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "HB", thr = "chla")
```

### Middle Tampa Bay

```{r chlplot_mtb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "MTB", thr = "chla")
```

### Lower Tampa Bay

```{r chlplot_ltb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "LTB", thr = "chla")
```

## Plot Mean Annual Light Attenuation Values by Bay Segment {.tabset}

### Old Tampa Bay

```{r laplot_otb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "OTB", thr = "la")
```

### Hillsborough Bay

```{r laplot_hb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "HB", thr = "la")
```

### Middle Tampa Bay

```{r laplot_mtb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "MTB", thr = "la")
```

### Lower Tampa Bay

```{r laplot_ltb, fig.height = 5, fig.width = 8}
show_thrplot(epcdata, bay_segment = "LTB", thr = "la")
```

### Target attainment matrix

```{r, fig.height = 12, fig.width = 4}
avedat <- anlz_avedat(epcdata)
anlz_attain(avedat, magdurout = T)
anlz_attain(avedat)
show_matrix(epcdata)
show_matrix(epcdata, tab = T)
```

