test_that("Checking anlz_tldcrk", {

  result <- tdldat %>%
    pull(score)

  expect_equal(result, c("Monitor", "No Data", "No Data", "Monitor", "No Data", "Monitor",
                         "Investigate", "Monitor", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Investigate", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Monitor", "No Data", "Monitor", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Monitor", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Caution", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "No Data", "No Data", "No Data", "Monitor", "Monitor", "No Data",
                         "No Data", "Monitor", "No Data", "No Data", "Prioritize", "No Data",
                         "No Data", "Monitor", "No Data", "Monitor", "No Data", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "Monitor", "No Data",
                         "No Data", "Monitor", "Caution", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Monitor", "No Data", "Monitor", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "No Data", "No Data", "No Data", "Monitor", "Prioritize", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Monitor", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "Investigate", "Prioritize", "Prioritize", "No Data", "Investigate",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Prioritize",
                         "No Data", "Investigate", "No Data", "No Data", "No Data", "Prioritize",
                         "Monitor", "Monitor", "Monitor", "No Data", "No Data", "Monitor",
                         "No Data", "No Data", "No Data", "Monitor", "Monitor", "Monitor",
                         "Monitor", "No Data", "No Data", "Caution", "No Data", "No Data",
                         "Monitor", "Monitor", "Monitor", "No Data", "No Data", "Monitor",
                         "No Data", "Monitor", "No Data", "Monitor", "Prioritize", "Monitor",
                         "Prioritize", "Prioritize", "No Data", "No Data", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "No Data", "No Data", "Monitor", "No Data", "No Data", "Prioritize",
                         "Monitor", "Monitor", "Prioritize", "Monitor", "Monitor", "Prioritize",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "Prioritize", "Investigate", "Monitor", "No Data", "Monitor",
                         "Investigate", "No Data", "Monitor", "No Data", "No Data", "Investigate",
                         "Prioritize", "No Data", "Caution", "No Data", "No Data", "Caution",
                         "No Data", "No Data", "Prioritize", "No Data", "Prioritize",
                         "No Data", "No Data", "No Data", "No Data", "Prioritize", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Caution",
                         "No Data", "Monitor", "No Data", "Monitor", "Monitor", "No Data",
                         "No Data", "No Data", "No Data", "Monitor", "Monitor", "Monitor",
                         "Monitor", "Investigate", "Investigate", "Monitor", "Monitor",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Monitor", "Monitor", "No Data", "Monitor", "Monitor",
                         "No Data", "Investigate", "Caution", "Monitor", "No Data", "No Data",
                         "Investigate", "No Data", "Investigate", "No Data", "Investigate",
                         "Investigate", "No Data", "Investigate", "Investigate", "No Data",
                         "No Data", "Investigate", "Monitor", "No Data", "Investigate",
                         "Monitor", "Monitor", "Prioritize", "Investigate", "Investigate",
                         "Monitor", "Monitor", "No Data", "Monitor", "Monitor", "Investigate",
                         "No Data", "No Data", "Monitor", "Monitor", "Caution", "No Data",
                         "Monitor", "No Data", "Monitor", "Investigate", "No Data", "Monitor",
                         "Monitor", "Monitor", "No Data", "Monitor", "Monitor", "Caution",
                         "Monitor", "Monitor", "Monitor", "Monitor", "Monitor", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Monitor", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Investigate", "No Data", "No Data", "No Data", "Prioritize",
                         "No Data", "No Data", "Monitor", "Monitor", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "Monitor", "No Data", "No Data", "No Data", "Investigate", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Monitor", "No Data", "Monitor", "No Data", "Monitor", "No Data",
                         "No Data", "No Data", "Caution", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Monitor", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Investigate", "No Data",
                         "No Data", "Monitor", "No Data", "No Data", "No Data", "Caution",
                         "Monitor", "No Data", "Investigate", "No Data", "Caution", "Monitor",
                         "Monitor", "Investigate", "Monitor", "No Data", "Monitor", "Monitor",
                         "Monitor", "Monitor", "Monitor", "Investigate", "No Data", "No Data",
                         "No Data", "No Data", "Monitor", "Caution", "Investigate", "No Data",
                         "Monitor", "Monitor", "Monitor", "Monitor", "Monitor", "No Data",
                         "No Data", "No Data", "Monitor", "Monitor", "Caution", "Monitor",
                         "No Data", "Monitor", "Monitor", "Monitor", "Monitor", "Monitor",
                         "Monitor", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "Caution", "No Data", "Monitor", "No Data", "Monitor", "Monitor",
                         "Monitor", "Investigate", "No Data", "Monitor", "Monitor", "Monitor",
                         "No Data", "Investigate", "Monitor", "Prioritize", "Monitor",
                         "Prioritize", "No Data", "No Data", "Investigate", "Prioritize",
                         "Investigate", "No Data", "No Data", "No Data", "No Data", "Monitor",
                         "No Data", "Caution", "No Data", "Monitor", "Monitor", "No Data",
                         "Caution", "No Data", "Monitor", "Monitor", "Caution", "No Data",
                         "No Data", "Caution", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Investigate",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Monitor", "No Data", "Monitor",
                         "No Data", "Investigate", "No Data", "Monitor", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Prioritize", "No Data", "Monitor",
                         "Caution", "Monitor", "Monitor", "Monitor", "Monitor", "Monitor",
                         "Monitor", "Investigate", "No Data", "Investigate", "No Data",
                         "No Data", "No Data", "No Data", "Monitor", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Monitor", "No Data", "No Data", "No Data", "Monitor",
                         "No Data", "Monitor", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Monitor", "No Data", "Prioritize",
                         "Prioritize", "No Data", "Monitor", "Monitor", "No Data", "Monitor",
                         "Prioritize"))

})
