test_that("Checking anlz_tldcrk", {

  result <- anlz_tdlcrk(tidalcreeks, iwrraw, yr= 2018) %>%
    pull(score)

  expect_equal(result, c("Target", "Target", "Target", "No Data", "No Data", "Target",
                         "No Data", "No Data", "Target", "No Data", "Target", "Target",
                         "Target", "No Data", "No Data", "Caution", "No Data", "No Data",
                         "Target", "Target", "Target", "No Data", "Act", "No Data", "Target",
                         "No Data", "No Data", "Target", "Act", "Target", "Act", "Act",
                         "No Data", "No Data", "No Data", "Target", "No Data", "No Data",
                         "No Data", "Target", "No Data", "No Data", "Target", "No Data",
                         "No Data", "Target", "Act", "Investigate", "Act", "Target", "Target",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Target", "Act", "Act", "Target", "No Data", "No Data", "Investigate",
                         "No Data", "Target", "No Data", "No Data", "No Data", "Act",
                         "No Data", "Caution", "No Data", "No Data", "Investigate", "No Data",
                         "Act", "No Data", "No Data", "No Data", "No Data", "Act", "No Data",
                         "No Data", "Act", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "Investigate", "Target", "Target", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Investigate", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Target", "Target", "No Data", "No Data",
                         "No Data", "Investigate", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Target", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Target", "No Data", "Target",
                         "No Data", "No Data", "No Data", "Target", "No Data", "Caution",
                         "No Data", "Target", "No Data", "Investigate", "Target", "No Data",
                         "Target", "Target", "Target", "No Data", "Target", "No Data",
                         "Investigate", "No Data", "No Data", "No Data", "No Data", "Target",
                         "Target", "Caution", "No Data", "Investigate", "No Data", "Act",
                         "No Data", "No Data", "Target", "Target", "Target", "Target",
                         "Target", "No Data", "No Data", "No Data", "Target", "Target",
                         "No Data", "Target", "Target", "Target", "Target", "No Data",
                         "Target", "No Data", "Target", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Target", "No Data", "Target",
                         "No Data"))

})
