test_that("Checking anlz_tldcrk", {

  result <- anlz_tdlcrk(tidalcreeks, iwrraw, yr= 2018) %>%
    pull(score)

  expect_equal(result, c("No Data", "No Data", "Green", "Green", "No Data", "No Data",
                         "Green", "Green", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Yellow", "No Data",
                         "Green", "Red", "No Data", "No Data", "No Data", "Green", "No Data",
                         "Green", "No Data", "No Data", "No Data", "Green", "Green", "Green",
                         "No Data", "Green", "Orange", "No Data", "No Data", "No Data",
                         "Green", "No Data", "Green", "No Data", "No Data", "Green", "No Data",
                         "Green", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Green", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Green",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Green", "No Data", "Green", "No Data",
                         "No Data", "Green", "No Data", "No Data", "No Data", "Green",
                         "No Data", "No Data", "Green", "Green", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Green", "No Data",
                         "Green", "Green", "No Data", "Green", "Green", "Green", "Green",
                         "No Data", "Green", "Green", "Green", "No Data", "Green", "Green",
                         "Green", "Green", "Green", "No Data", "No Data", "Green", "Green",
                         "Green", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Green", "Green", "No Data", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Green", "Green",
                         "Green", "Green", "Red", "Green", "Orange", "Green", "Green",
                         "Green", "Green", "Green", "Orange", "Green", "Green", "Green",
                         "No Data", "Green", "Green", "Green", "No Data", "Green", "Green",
                         "No Data", "No Data", "Green", "No Data", "Green", "Green", "Green",
                         "No Data", "No Data", "Yellow", "No Data", "No Data", "Green",
                         "Green", "Green", "No Data", "Red", "No Data", "Green", "Green",
                         "No Data", "Green", "Red", "Green", "Red", "Red", "No Data",
                         "No Data", "No Data", "Green", "Green", "Green", "No Data", "Green",
                         "Green", "No Data", "Green", "Green", "No Data", "Green", "Red",
                         "Orange", "Red", "Green", "Green", "Green", "Green", "No Data",
                         "No Data", "No Data", "No Data", "Green", "Red", "Red", "Green",
                         "Green", "No Data", "Orange", "No Data", "Green", "Green", "No Data",
                         "Green", "Red", "No Data", "Yellow", "No Data", "No Data", "Orange",
                         "No Data", "Red", "No Data", "No Data", "Green", "Green", "Red",
                         "No Data", "No Data", "Red", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Orange", "Green", "Green", "No Data", "No Data",
                         "No Data", "No Data", "Green", "Green", "Green", "Green", "Green",
                         "Green", "No Data", "No Data", "Green", "No Data", "No Data",
                         "No Data", "Green", "No Data", "No Data", "No Data", "Green",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Green", "No Data", "Green",
                         "Green", "No Data", "Green", "Green", "No Data", "Green", "No Data",
                         "Green", "No Data", "No Data", "Green", "Green", "Green", "Green",
                         "No Data", "Orange", "Green", "No Data", "Orange", "No Data",
                         "Orange", "Green", "No Data", "Orange", "Orange", "No Data",
                         "Green", "Green", "Green", "No Data", "Green", "Orange", "Green",
                         "Green", "Red", "Orange", "Green", "Green", "Orange", "No Data",
                         "Green", "No Data", "No Data", "Green", "Green", "No Data", "No Data",
                         "Green", "Orange", "Green", "Green", "Green", "Green", "No Data",
                         "Green", "No Data", "Green", "Yellow", "Green", "Green", "Green",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "No Data", "Green", "No Data", "No Data", "Green",
                         "Green", "No Data", "Orange", "Green", "No Data", "Green", "Green",
                         "No Data", "Green", "No Data", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Green", "No Data", "No Data", "Green", "Green", "Green",
                         "No Data", "Green", "No Data", "Orange", "No Data", "No Data",
                         "No Data", "Green", "No Data", "No Data", "No Data", "Green",
                         "No Data", "Green", "No Data", "No Data", "Green", "No Data",
                         "Green", "No Data", "No Data", "No Data", "No Data", "Green",
                         "No Data", "No Data", "No Data", "Green", "No Data", "Green",
                         "No Data", "No Data", "No Data", "Green", "No Data", "No Data",
                         "No Data", "Green", "No Data", "No Data", "No Data", "No Data",
                         "No Data", "Green", "Green", "Green", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "Green", "No Data",
                         "No Data", "No Data", "No Data", "No Data", "No Data", "Green",
                         "No Data", "Yellow", "No Data", "Green", "Green", "Orange", "Green",
                         "No Data", "Green", "Green", "Green", "No Data", "Green", "No Data",
                         "Orange", "No Data", "No Data", "Green", "Green", "Green", "Green",
                         "Yellow", "No Data", "Orange", "Green", "Red", "No Data", "No Data",
                         "Green", "Green", "Green", "Green", "Green", "Green", "No Data",
                         "No Data", "Green", "Green", "Green", "Green", "Green", "Green",
                         "Green", "No Data", "Green", "No Data", "Green", "No Data", "No Data",
                         "No Data", "No Data", "No Data", "Green", "Green", "No Data",
                         "Green", "No Data", "Green", "Green", "Green", "Green", "Green",
                         "Green", "Red", "Green", "Green", "Green", "Green", "Yellow",
                         "Green", "No Data", "Green", "Green", "Green", "Green", "Orange",
                         "Green", "No Data", "Green", "No Data", "Green", "No Data", "No Data",
                         "No Data", "Yellow", "Green", "No Data", "No Data", "Green",
                         "No Data", "Green", "No Data", "Green", "No Data", "Green", "No Data",
                         "Green", "No Data", "Green", "Green", "No Data", "Green", "No Data",
                         "Green", "Green", "No Data", "Green", "No Data", "No Data", "Green",
                         "No Data", "No Data", "No Data", "Green", "Green", "No Data",
                         "No Data", "No Data", "Green", "No Data", "No Data", "No Data",
                         "No Data"))

})
