#' Enterococcus station location metadata
#'
#' @format A data frame with 50 rows and 5 columns:
#' \describe{
#'  \item{station}{character, sample station, as named in the Water Quality Portal}
#'  \item{latitude}{numeric, latitude in decimal degrees}
#'  \item{longitude}{numeric, longitude in decimal degrees}
#'  \item{bay_segment}{character, full name of Bay Segment in which the station lies}
#'  \item{bay_segment_abbrev}{character, abbreviated version of Bay Segment in which the station lies}
#' }
#' @details Latitude, Longitude, and Bay Segment information for each of the identified key Enterococcus stations. Generated by \code{data-raw/entero_stationdata-raw.R} (view on github: \url{https://github.com/tbep-tech/tbeptools/blob/master/data-raw/entero_stationdata-raw.R})
#'
#' @source Lat/Long information from Water Quality Portal, \url{https://waterqualitydata.us}
#'

"entero_stationdata"
